auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("",views.re_path),
    path("Error404/UnknownPath",views.Error404,name="Error"),
    path("<str:listing_name>", views.index, name="index"),
    path("accounts/login/", views.login_view, name="login"),
    path("accounts/logout", views.logout_view, name="logout"),
    path("accounts/register", views.register, name="register"),
    path("accounts/listing/create",views.create, name="create"),
    path("listing/<int:listing_id>", views.listing, name="listing"),
    path("listing/<int:listing_id>/watchlist", views.watchlist, name = "watchlist"),
    path("<str:listing_name>/category", views.category, name="category"),
    path("listing/<int:listing_id>/bidding", views.bidaction, name="bid"),
    path("listing/<int:listing_id>/comment", views.comment, name="comment"),
    path("listing/<int:listing_id>/reply/<int:comment_id>", views.reply, name="reply")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]
handler404 = 'auctions.views.handler404'

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import Max
from django.utils import timezone
from datetime import datetime
import decimal
import calendar
LISTING_CATEGORIES = (
    ('ALL', 'Choose...'),
    ('BOOKS', 'Books'),
    ('MUSIC', 'Music'),
    ('MOVIES', 'Movies'),
    ('GAMES', 'Games'),
    ('COMPUTERS', 'Computers'),
    ('ELECTRONICS', 'Electronics'),
    ('KITCHEN', 'Kitchen'),
    ('HOME', 'Home'),
    ('HEALTH', 'Health'),
    ('PETS', 'Pets'),
    ('TOYS', 'Toys'),
    ('FASHION', 'Fashion'),
    ('SHOES', 'Shoes'),
    ('SPORTS', 'Sports'),
    ('BABY', 'Baby'),
    ('TRAVEL', 'Travel')
)

def td_format(td_object):
        seconds = int(td_object.total_seconds())
        periods = [
            ('year',        60*60*24*365),
            ('month',       60*60*24*30),
            ('day',         60*60*24),
            ('hour',        60*60),
            ('minute',      60),
            ('second',      1)
        ]

        strings = []
        for period_name, period_seconds in periods:
            if seconds >= period_seconds:
                period_value, seconds = divmod(seconds, period_seconds)
                has_s = 's' if period_value > 1 else ''
                strings.append("%s %s%s" % (period_value, period_name, has_s))
                break

        return ", ".join(strings)

class User(AbstractUser):
    watchlist = models.ManyToManyField(
        "Listing", blank=True, related_name="watchlist")


class Listing(models.Model):
    creator = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="listings", null=True)
    title = models.CharField(max_length=200, verbose_name="Title")
    description = models.TextField(verbose_name="Description")
    price = models.DecimalField(
        decimal_places=2, verbose_name="Starting Bid", max_digits=10)
    image = models.URLField(blank=True, verbose_name="Image URL", null=True)
    category = models.CharField(choices=LISTING_CATEGORIES, blank=True,
                                verbose_name="Category", max_length=200, null=True)
    active = models.BooleanField(default=True)
    winner = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True, null=True)

    def date_time(self):
        date_time = (str(self.timestamp)).split(" ")
        mydate = datetime.strptime(date_time[0],'%Y-%m-%d')
        return f"{(calendar.day_abbr[self.timestamp.weekday()])}, {calendar.month_abbr[mydate.month]} {mydate.day} {mydate.year}"
        # return f"{self.timestamp.weekday()} {date_time[0][2]} {date_time[1][1]} {date_time[2][3]} "

    def __str__(self):
        return self.title
    
    def get_user_bids(self,request):
        t= request.user.bids.filter(listing = self)
        return t

    def get_highestbid(self):
        t = Bid.objects.filter(listing=self).order_by("bid_price").reverse()
        return t


class Bid(models.Model):
    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="bids", null=True)
    bidder = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="bids", null=True)
    timestamp = models.DateTimeField(auto_now_add=True, null=True)
    bid_price = models.DecimalField(
        decimal_places=2, verbose_name="Bid Price", max_digits=15, null=True)

    def date(self):
        return td_format(timezone.now() - self.timestamp)
    
    def __str__(self):
        return f"{self.bidder} bid ${self.bid_price} for {self.listing}"


class Comment(models.Model):
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="comments", null=True)
    commenter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments", null=True)
    content = models.TextField(verbose_name="Comment", default="")
    timestamp = models.DateTimeField(auto_now_add=True, null=True)

    def date_time(self):
        return td_format(timezone.now() - self.timestamp)

    def __str__(self):
        return f"{self.commenter} commented on {self.listing} ({self.timestamp.date()})"

class Replies(models.Model):
    commenter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reply", null=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="reply", null = True)
    content = models.TextField(verbose_name="Replies", default="", null=True)
    timestamp = models.DateTimeField(auto_now_add=True, null=True)
    
    def date_time(self):
        return td_format(timezone.now() - self.timestamp)
        
    def __str__(self):
        return f"{self.commenter} replied to {self.comment} ({self.timestamp.date()})"

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django import forms
from .models import User, Listing, LISTING_CATEGORIES, Bid, Comment, Replies


class CreateListing (forms.Form):
    model = Listing
    title = forms.CharField(max_length=30, label="Title*", label_suffix="", widget=forms.TextInput(
        attrs={'placeholder': 'Enter the product title', 'autofocus': 'autofocus'}))
    price = forms.DecimalField(decimal_places=2, label="Starting Bid*", label_suffix="",
                               widget=forms.NumberInput(attrs={'placeholder': 'Enter initial Bid'}), min_value=1, max_value=999999999)
    image = forms.URLField(required=False, label="Image URL", label_suffix="",
                           widget=forms.TextInput(attrs={'placeholder': 'Enter image URL'}))
    category = forms.ChoiceField(choices=LISTING_CATEGORIES, label_suffix="")
    description = forms.CharField(widget=forms.Textarea(
        attrs={'placeholder': 'Enter product description '}), label="Description*", label_suffix="")


class categoryForm(forms.Form):
    category = forms.ChoiceField(choices=LISTING_CATEGORIES)
    category.widget.attrs.update(
        {'class': 'selector', 'onchange': 'this.form.submit()'})


class commentForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea(
        attrs={"class": "form-control", "cols": "30", "rows": "3"}))


def handler404(request, *args, **kwargs):
    return HttpResponseRedirect(f"/Error404/UnknownPath")


def Error404(request):
    return render(request, "auctions/PageNotFound.html")


def re_path(request):
    return HttpResponseRedirect(f"/activeListings")


def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                messages.success(
                    request, f"Successfully Logged in as {username} <br> Create a new listing below")
                return HttpResponseRedirect(request.POST.get('next'))
            else:
                messages.success(
                    request, f"Successfully Logged in as {username}")
                return HttpResponseRedirect('/')
        else:
            messages.error(
                request, "Invalid username and/or password <br> Note that both fields may be case-sensitive")
            return HttpResponseRedirect(reverse('login'))
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    messages.success(request, "Logged out successfully")
    return HttpResponseRedirect('/')


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords doesn't match"
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken"
            })
        login(request, user)
        messages.success(
            request, f"Successfully registered as {username} <br> Check in email for confirmation")
        return HttpResponseRedirect(reverse("index", args=('activeListings',)))
    else:
        return render(request, "auctions/register.html")


@login_required
def create(request):
    if request.method == "POST":
        form = CreateListing(request.POST)
        if form.is_valid() and (form.cleaned_data["category"] != "ALL"):
            title = (form.cleaned_data["title"]).strip()
            description = (form.cleaned_data["description"]).strip()
            price = form.cleaned_data["price"]
            image = form.cleaned_data["image"]
            category = form.cleaned_data["category"]
            listing = Listing(creator=request.user, title=title,
                              description=description, price=price, image=image, category=category)
            bid = Bid(listing=listing, bidder=request.user, bid_price=price)
            listing.save()
            bid.save()
            messages.success(
                request, f"Created a listing named \"{title}\" successfully")
            return HttpResponseRedirect(reverse("index", args=('activeListings',)))
        elif form.is_valid():
            messages.error(request, f"Catagory should not be left empty")
            return render(request, "auctions/create.html", {
                "listing_form": form
            })
        else:
            messages.error(
                request, f"Error occured while translating image URL")
            return render(request, "auctions/create.html", {
                "listing_form": form
            })
    return render(request, "auctions/create.html", {
        "listing_form": CreateListing()
    })


def bidaction(request, listing_id):
    listing = Listing.objects.get(pk=listing_id)
    if request.method == "POST":
        bid_price = request.POST["bidding_price"]
        bid = Bid(listing=listing, bidder=request.user, bid_price=bid_price)
        bid.save()
        messages.success(
            request, f"We have recieved your bid at ${bid_price} successfully")
    else:
        listing.active = False
        if listing.bids.all().count() < 2:
            messages.success(request, f"The auction was closed with 0 Bids")
        else:
            listing.winner = listing.get_highestbid()[0].bidder
            messages.success(
                request, f"The auction was closed successfully with {listing.winner} as the winner")
        listing.save()

    return HttpResponseRedirect(reverse("listing", args=(listing_id,)))


@login_required
def watchlist(request, listing_id):
    listing = Listing.objects.get(pk=listing_id)
    if listing in request.user.watchlist.all():
        request.user.watchlist.remove(listing)
        messages.success(request, "Successfully removed from your watchlist")
    else:
        request.user.watchlist.add(listing)
        messages.success(request, "Successfully added to your watchlist")
    return HttpResponseRedirect(f"/listing/{listing.id}")


def category(request, listing_name):
    if request.method == "POST":
        form = categoryForm(request.POST)
        if form.is_valid():
            value = form.cleaned_data["category"]
            if value == "ALL":
                return HttpResponseRedirect(reverse("index", args=('activeListings',)))
            listings, stat = None, None
            if listing_name == "activeListings":
                listings = Listing.objects.filter(active=True, category=value)
                stat = "Active Listings"
            elif listing_name == "allListings":
                listings = Listing.objects.filter(category=value)
                stat = "All Listings"
            elif listing_name == "myWatchlist" and request.user.is_authenticated:
                listings = request.user.watchlist.filter(category=value)
                stat = "My Watchlist"
            elif listing_name == "myListings" and request.user.is_authenticated:
                listings = request.user.listings.filter(category=value)
                stat = "My Listings"

            if listings is not None:
                return render(request, "auctions/index.html", {
                    "listings": listings,
                    "stat": (stat, listing_name),
                    "options": form
                })
            else:
                return HttpResponseRedirect(reverse("index", args=('activeListings',)))
        else:
            return HttpResponseRedirect(reverse("index", args=('activeListings',)))
    return HttpResponseRedirect(f"/Error404/UnknownPath")


def index(request, listing_name):
    listings, stat = None, None
    if listing_name == "activeListings":
        listings = Listing.objects.filter(active=True)
        stat = "Active Listings"
    elif listing_name == "allListings":
        listings = Listing.objects.all()
        stat = "All Listings"
    elif listing_name == "myWatchlist" and request.user.is_authenticated:
        listings = request.user.watchlist.all()
        stat = "My Watchlist"
    elif listing_name == "myListings" and request.user.is_authenticated:
        listings = request.user.listings.all()
        stat = "My Listings"

    if listings is not None:
        return render(request, "auctions/index.html", {
            "listings": listings,
            "stat": (stat, listing_name),
            "options": categoryForm()
        })
    else:
        return HttpResponseRedirect(f"/Error404/UnknownPath")


def listing(request, listing_id):
    listing = Listing.objects.get(pk=listing_id)
    if request.user.is_authenticated:
        biduser = Bid.objects.filter(listing=listing, bidder=request.user)
    else:
        biduser = None
    comments = Comment.objects.filter(listing=listing)
    tcoms = 0
    for comment in comments:
        tcoms += comment.reply.all().count() + 1

    return render(request, "auctions/listing.html", {
        "listing": listing,
        "highest_bid": listing.get_highestbid()[0],
        "biduser": biduser,
        "commentForm": commentForm(),
        "comments": comments,
        "totalcomments": tcoms
    })


@login_required

auctions/templates/auctions/PageNotFound.html
{% extends "auctions/layout.html" %}
{% block title %}
Error 404
{% endblock %}
{% block body %}
<div class="text-center card w-100 p-4">
    <span class="display-1 font-weight-bold" style="color: rgb(255, 175, 1);letter-spacing: 5px;">404</span>
    <h1 class="display-h1 text-bold" style="letter-spacing: 1px;">PAGE NOT FOUND</h1>
    <h4 class="mt-5 mb-3 lead">Please make sure the spelling is correct </h4>
    <a href="{% url 'index' 'activeListings' %}"><button class="btn back-color btn-md w-25 ">
        HOME PAGE
    </button></a>
</div> 
{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %} {% block active %}create{% endblock %} {% block style %}
<style>
    
    form label {
        font-size: 12px;
        margin-bottom: -4px;
    }
    
    form input,
    #id_description {
        outline: none;
        border: none;
        font-size: 16px;
        padding: 2px 0 10px 0;
        border-bottom: solid 1px rgb(192, 191, 191);
        margin: 4px 0 20px 0;
        width: 80%;
    }
    
    form input:focus,
    #id_description:focus {
        border-bottom: solid 2px #007bff;
    }
    
    #id_description {
        height: 200px;
    }
    
    #id_category {
        width: 200px;
        padding: 6px;
        font-size: 16px;
        border-radius: 10px 0px 10px 0;
        outline: none;
    }
    
    #id_category:focus {
        border: #007bff solid 2px;
    }
    
</style>
{% endblock %} {% block body %}
    <h1 class="text-primary font-weight-bolder mb-4">Create a New Listing</h1>
    <form action="{% url 'create' %}" method="POST">
        {% csrf_token %} 
        <div class="form-group">
            {{listing_form.title.label_tag}}
            <br>
            {{listing_form.title}}
        </div>
        <div class="form-group">
            {{listing_form.description.label_tag}}
            <br>
            {{listing_form.description}}
        </div>
        <div class="form-group">
            {{listing_form.price.label_tag}}
            <br>
        {{listing_form.price}}
        </div>
        <div class="form-group">
            {{listing_form.image.label_tag}}
            <br>
            {{listing_form.image}}
        </div>
        <div class="form-group">
            {{listing_form.category.label_tag}}
            <br>
            {{listing_form.category}}
        </div>
        <br>
        <input class="btn btn-primary" style="border-radius: 10px 10px 0 0;" type="submit" value="Add Listing">
    </form>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load static %}
{% block title %}Auctions{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'auctions/main.css' %}">
{% endblock %}



{% block body %}
<h1 class="title-label">{{stat.0}}
    <div class="select-category">
        <form method="POST" action="{% url 'category' stat.1 %}">
            {% csrf_token %}
            {{options.category}}
        </form>
    </div>
</h1>
<div class="container-index">
    {% for listing in listings %}
    <div class="card-index">
        {% if listing.image %}
        <section class="img">
            <img src="{{listing.image}}" alt="{{listing.title}}">
        </section>
        {% endif %}
        <section class="content-section {% if not listing.image %}invalid-img{% endif %}">
            {% if user.is_authenticated %}
            <div class="card-header-watchlist">
                <a href="{% url 'watchlist' listing.id %}" title="{% if listing in request.user.watchlist.all%}Remove from watchlist{% else %}Add to watchlist{% endif %}">
                    <i class="{% if listing in request.user.watchlist.all%}fas{% else %}far{% endif %} fa-heart"></span></i>
                </a>
            </div>
            {% endif %}
            <div class="content">
                <span class="date-creator">{{listing.date_time}} | {{listing.category|lower|title}}
                <br>Created by {{listing.creator}}</span>
                <h1 class="card-title mt-4 mb-0">{{listing.title}}
                    {% if not listing.active %}
                    <br><a href="#"><button class="btn back-color">Closed</button></a>
                    {% endif %}

                </h1>
                <p class="card-description mb-5 mt-4 font-italic">{{listing.description|truncatewords:50}}</p>
            </div>
            <div class="card-footer-index text-center"><a href="{%url 'listing' listing.id %}" class="view-more">View More</a></div>
        </section>
    </div>
    {% empty %}
    <h3 class="text-center btn-dark p-2 winner" style="border-radius: 10px;">Nothing to show here</h3>
    {% endfor %}
</div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{%endblock%}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'auctions/styles.css' %}">
    {% block style %}{% endblock %}
</head>

<body>
    <header class="my-header">
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index' 'activeListings' %}"><i class="fas fa-gavel icon-mr-right"></i> Auctions</a>
                
                <div>
                <span class="text-secondary nli2 icon-mr-right">Not Logged In</span>
                 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                   <span class="navbar-toggler-icon"><i class="fas fa-bars" style="color:#fff; font-size:28px;"></i></span>
                 </button>
                </div>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item {% if stat.0 == 'Active Listings' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'index' 'activeListings' %}">Active</a>
                        </li>
                        <li class="nav-item {% if stat.0 == 'All Listings' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'index' 'allListings' %}">All Listings</a>
                        </li>
                        <li class="nav-item {% if request.resolver_match.url_name == 'create' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'create' %}">Create New Listing</a>
                        </li>
                    </ul>
                    {% if user.is_authenticated %}
                    <div class="navbar-nav dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user mr-auto icon-mr-right"></i>{{user.username}}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'index' 'myWatchlist' %}"><button type="button" class="btn">
                                    My Watchlists <span class="badge badge-dark">{{request.user.watchlist.all.count}}</span>
                                </button></a>
                            <a class="dropdown-item" href="{% url 'index' 'myListings' %}"><button type="button" class="btn">
                                    My Listings <span class="badge badge-dark">{{request.user.listings.all.count}}</span>
                                </button></a>
                            <div class="dropdown-divider">
                                
                            </div>
                            <a class="dropdown-item logout" href="{% url 'logout' %}"><button class="btn back-color w-100">Logout</button></a>
                        </div>
                    </div>
                    {% else %}
                    <div class="navbar-nav d-flex flex-row">
                        <span class="text-secondary nav-link nli icon-mr-right">Not Logged In</span>
                        <a href="{% url 'login' %}" class="icon-mr-right"><button class="btn back-color">Login</button></a>
                        <a href="{% url 'register' %}" class="icon-mr-right"><button class="btn back-color">Signup</button></a>
                    </div>
                    {% endif %}
                </div>
                
                {% if messages %}
                <input class="d-none" type="checkbox" id="close">
                {% for message in messages %}
                <div class="alert {% if message.tags == 'success' %} alert-success {% else %} alert-danger {% endif %} text-center messages" role="alert">
                  {{message|safe}}
                  <label for="close" class="messages-cross px-2">
                    <i class="fas fa-times"></i>
                  </label>
                </div>
                {% endfor %}
                {% endif %}
            </div>
        </nav>
        <div class="intro-2">
            he
        </div>
    </header>

    <main class="container main-body my-5">
        {% block body %}{% endblock %}
    </main>

    <footer class="footer bg-dark">
        <div class="container text-center d-flex justify-content-center">
            <span class="text-muted align-middle" style="margin: 20px 0;">Copyrights © Auctions 2020 All rights reserved</span>
        </div>
    </footer>

    <script src="https://kit.fontawesome.com/b6f67b378e.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

auctions/templates/auctions/login.html
{% extends "auctions/users.html" %}

{% block title %}Login{% endblock %}

{% block titlestatus%}Login Here{% endblock %}

{% block form %}
<form action="{% url 'login' %}" method="post">
    {% csrf_token %}
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <label for="username" class="label-credetials">Username</label>
    <div class="input-field">
        <i class="fas fa-user"></i>
        <input type="text" placeholder="Enter Username" autofocus class="input-credentials" name="username" required autocomplete="off">
    </div>
    <label for="password" class="label-credetials">Password</label>
    <div class="input-field">
        <i class="fas fa-lock"></i>
        <input type="password" placeholder="Enter Password" class="input-credentials" name="password" required>
    </div>
    <input type="submit" value="Login">
</form>
{% if messages %}
{% for message in messages %}
<h1 id = "title" style="font-size: 12px; margin-top: 0; text-align: center; color: red;">{{message|safe}}</h1>
{% endfor%}
{% endif %}
{% endblock %}

{% block links %}
<a href="{% url 'register' %}">New User?</a>
{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/users.html" %}

{% block title %}Register{% endblock %}

{% block titlestatus%}Get Started{% endblock %}

{% block form %}
<form action="{% url 'register' %}" method="post">
    {% csrf_token %}
    <label for="username" class="label-credetials">Username</label>
    <div class="input-field">
        <i class="fas fa-user"></i>
        <input type="text" placeholder="Enter Username*" autofocus class="input-credentials" name="username" required autocomplete="off">
    </div>
    <label for="Email Address" class="label-credetials">Email Address</label>
    <div class="input-field">
        <i class="fas fa-envelope"></i>
        <input type="email" placeholder="Enter Email*" class="input-credentials" name="email" required autocomplete="off">
    </div>
    <label for="password" class="label-credetials">Password</label>
    <div class="input-field">
        <i class="fas fa-lock"></i>
        <input type="password" placeholder="Enter Password*" class="input-credentials" name="password" required>
    </div>
    <label for="Confirm" class="label-credetials">Confirm Password</label>
    <div class="input-field">
        <i class="fas fa-lock"></i>
        <input type="password" placeholder="Confirm Password*" class="input-credentials" name="confirmation" required>
    </div>
    <input type="submit" value="Register">
</form>
{% if message %}
<h1 id = "title" style="font-size: 12px; margin-top: 0; text-align: center;color: red;">{{message}}</h1>
{% endif %}
{% endblock %}

{% block links %}
<a href="{% url 'login' %}">Already a user?</a>
{% endblock %}

auctions/templates/auctions/users.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'auctions/user.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/b6f67b378e.js" crossorigin="anonymous"></script> 
</head>
<body>
    <a href="{% url 'index' 'activeListings' %}"><button class="home">HOME</button></a>
    <div id="login-back">
        <img id="user" src="{% static 'auctions/user.jpg'%}" alt="USER">
        <h1 id="title">{% block titlestatus%}{% endblock %}</h1>
        {% block form %}
        {% endblock %}
        <div class="links">
            {% block links %}
            {% endblock %}
        </div>
    </div>
</body>
</html>